# Exercise 1
An art gallery wants to digitalize their inventory and sales records. Your task is to design a database that will keep track of artworks, artists, customers, and sales.

Artworks have unique identifiers, titles, creation dates, types (e.g., painting, sculpture), and price tags. Artists, identified by a unique identifier, have first and last names, birthplaces, and styles (e.g., impressionist, modern). Customers have unique identifiers, names, and contact details (feel free to come up with relevant contact information).

When a sale is made, the database should record the date, the customer, and the artwork sold. Each artwork can be associated with one artist, but artists can create multiple artworks. Customers can purchase multiple artworks over time.

Design a data model for this art gallery system. Make sure to define all necessary fields, data types, and relationships.

## Solution
The following diagram shows the solution:

![art gallery model](../../Databases/Extra%20Exercises/img/art_gallery.png)

The following mysql script creates the database and the tables for the art gallery system:

```mysql
CREATE DATABASE art_gallery;
USE art_gallery;

CREATE TABLE artists (
    artist_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    birthplace VARCHAR(255) NOT NULL,
    email VARCHAR(30),
    phone_number VARCHAR(15),
    address VARCHAR(100),
    instagram VARCHAR(30),
    style VARCHAR(255) NOT NULL
);

CREATE TABLE artworks (
    artwork_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    creation_date DATE NOT NULL,
    type VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    artist_id INT NOT NULL,
    FOREIGN KEY (artist_id) REFERENCES artists(artist_id)
);

CREATE TABLE customers (
    customer_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    contact VARCHAR(255) NOT NULL
);

CREATE TABLE sales (
    sale_id INT AUTO_INCREMENT PRIMARY KEY,
    sale_date DATE NOT NULL,
    customer_id INT NOT NULL,
    artwork_id INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (artwork_id) REFERENCES artworks(artwork_id)
);
```


# Exercise 2
You need to design a database for an organization that manages various popular races in the city of Valencia. The database should keep track of events, participants, race results, and sponsors, specifically:


- **Events:** Each event has a unique identifier, name (e.g., "Valencia Marathon"), type (e.g., marathon, triathlon), location, date, and distance.

- **Participants:** Participants are individuals who register for events. For each participant, the database should store a unique ID, name, age, gender, and contact information (feel free to had here the fields you consider relevant).

- **Race Results:** After each event, the race results are recorded. This includes the participantâ€™s ID, event ID, finish time, and overall position in the event.

- **Sponsors:** Various organizations sponsor events. For each sponsor, store a unique ID, name, contact information, and the events they sponsor.

- Registrations:** Participants register for specific events. Each registration links a participant to an event and includes details like the registration date and the category (e.g., amateur, professional).


Design a database for this race event management system. Include all necessary entities, fields,  and relationships. Ensure your design can support queries for participant race history, event details, sponsorship information, and event management.

## Solution
The following diagram shows the solution:
![event manager model](../../Databases/Extra%20Exercises/img/event_manager.png)

The following code snippet shows the solution:

```mysql
CREATE DATABASE event_manager;
USE event_manager;

CREATE TABLE events (
    event_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    distance DECIMAL(10,2) NOT NULL
);

-- Create participants table
CREATE TABLE participants (
    participant_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    email VARCHAR(30),
    phone_number VARCHAR(15),
    address VARCHAR(100),
    instagram VARCHAR(30)
);

-- Create sponsors table
CREATE TABLE sponsors (
    sponsor_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(30),
    phone_number VARCHAR(15),
    address VARCHAR(100),
    instagram VARCHAR(30)
);

-- Create registrations table
CREATE TABLE registrations (
    registration_id INT AUTO_INCREMENT PRIMARY KEY,
    registration_date DATE NOT NULL,
    category VARCHAR(255) NOT NULL,
    participant_fk INT NOT NULL,
    event_fk INT NOT NULL,
    FOREIGN KEY (participant_fk) REFERENCES participants(participant_id),
    FOREIGN KEY (event_fk) REFERENCES events(event_id)
);

-- Create sponsorships table (M:N relationship)
CREATE TABLE sponsorships (
    sponsorship_id INT AUTO_INCREMENT PRIMARY KEY,
    sponsor_fk INT NOT NULL,
    event_fk INT NOT NULL,
    FOREIGN KEY (sponsor_fk) REFERENCES sponsors(sponsor_id),
    FOREIGN KEY (event_fk) REFERENCES events(event_id)
);

-- Create race_results table (M:N relationship)
CREATE TABLE race_results (
    race_result_id INT AUTO_INCREMENT PRIMARY KEY,
    finish_time TIME NOT NULL,
    overall_position INT NOT NULL,
    participant_fk INT NOT NULL,
    event_fk INT NOT NULL,
    FOREIGN KEY (participant_fk) REFERENCES participants(participant_id),
    FOREIGN KEY (event_fk) REFERENCES events(event_id)
);
```



## Exercise 3
The following diagram shows a database for an Internet of Things system:

![iiot model](https://github.com/ffraile/database_tutorials/blob/main/Extra%20Exercises/img/iiot.png?raw=true)


Try to build the following ```SELECT``` queries to analyse the data in the database.

1. Write a ```SELECT``` query to know the date of the most recent ```recent_value``` for every sensor

The following query shows the solution:

```mysql
SELECT sensor_id, MAX(date) AS most_recent_date
FROM sensor_data
GROUP BY sensor_id;
```


2. Write a ```SELECT``` query to show the different sensors of device with ID 1

The following query shows the solution:

```mysql
SELECT sensor_id
FROM sensors
WHERE device_fk = 1;
```